[program:eu-catalog-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/waylander/Projects/eu-catalog/artisan queue:work database --tries=1 --timeout=600 --sleep=3 --max-jobs=500
directory=/home/waylander/Projects/eu-catalog
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/home/waylander/Projects/eu-catalog/storage/logs/queue-worker.log
stopwaitsecs=620
